version: "3"

services:
        nginxproxy:
                image: nginx:latest
                depends_on:
                        - nginx
                        - springboot
                        - db
                        - redis
                ports:
                        - "80:80"
                restart: always
                volumes:
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        nginx:
                build: ./frontend
                restart: always

        db:
                image: mariadb:latest
                restart: always
                environment:
                        MARIADB_DATABASE: test
                        MARIADB_USER: test
                        MARIADB_PASSWORD: 1234
                        MARIADB_ROOT_PASSWORD: 1q2w3e4r!@#
                volumes:
                        - ./db/data/mysql:/var/lib/mysql
                        - ./db/cnf:/etc/mysql/conf.d
                ports:
                        - "3306"
        redis:
                image: redis:alpine
                volumes:
                        - ./redis/data:/data
        springboot:
                build: ./backend
                restart: always
                environment:
                        SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/test?useUnicode=true
                        SPRING_DATASOURCE_USERNAME: test
                        SPRING_DATASOURCE_PASSWORD: 1234
                ports:
                        - "8080"
                depends_on:
                        - db
                        - redis
