version: "3"

services:
        nginxproxy:
                image: nginx:latest
                depends_on:
                        - nginx
                        - springboot
                        - db
                        - redis
                ports:
                        - "80:80"
                        - "443:443"
                restart: always
                volumes:
                        #– ./myweb:/usr/share/nginx/html
      		#– ./certbot-etc:/etc/letsencrypt
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        nginx:
                build: ./frontend
                restart: always

        db:
                image: mariadb:latest
                restart: always
                environment:
                        MARIADB_DATABASE: test
                        MARIADB_USER: test
                        MARIADB_PASSWORD: 1q2w3e4r!@#
                        MARIADB_ROOT_PASSWORD: 1q2w3e4r!@#
                volumes:
                        – ./cnf/db/cnf:/etc/mysql/conf.d
                ports:
                        - "3306:3306"
        redis:
                image: redis:alpine
        springboot:
                build: ./backend
                restart: always
                environment:
                        SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/test?useUnicode=true
                        SPRING_DATASOURCE_USERNAME: test
                        SPRING_DATASOURCE_PASSWORD: 1q2w3e4r!@#
                ports:
                        - "8080"
                depends_on:
                        - db
                        - redis
        #certbot:
        #       depends_on:
        #                - nginxproxy
        #        image: certbot/certbot
        #        volumes:
        #                – ./certbot-etc:/etc/letsencrypt
        #                – ./myweb:/usr/share/nginx/html
        #	      command: certonly --weboot --webroot-path=/usr/share/nginx/html --email "인증서 재발급시 필요한 인증 메일 주소" --agree-tos --no-eff-email -d “서버 주소 도메인”--keep-until-expiring