const baseAlcohol: object[] = [
  {
    id: 179,
    name: "Dark Rum",
    nameKr: "다크럼",
    img: "https://www.thecocktaildb.com/images/ingredients/Dark Rum-Small.png",
  },
  {
    id: 4,
    name: "Tequila",
    nameKr: "데킬라",
    img: "https://www.thecocktaildb.com/images/ingredients/Tequila-Small.png",
  },
  {
    id: 305,
    name: "Light Rum",
    nameKr: "라이트 럼",
    img: "https://www.thecocktaildb.com/images/ingredients/Light Rum-Small.png",
  },
  {
    id: 3,
    name: "Rum",
    nameKr: "럼",
    img: "https://www.thecocktaildb.com/images/ingredients/Rum-Small.png",
  },
  {
    id: 1,
    name: "Vodka",
    nameKr: "보드카",
    img: "https://www.thecocktaildb.com/images/ingredients/Vodka-Small.png",
  },
  {
    id: 71,
    name: "Bourbon",
    nameKr: "부르봉",
    img: "https://www.thecocktaildb.com/images/ingredients/Bourbon-Small.png",
  },
  {
    id: 74,
    name: "Brandy",
    nameKr: "브랜디",
    img: "https://www.thecocktaildb.com/images/ingredients/Brandy-Small.png",
  },
  {
    id: 97,
    name: "Champagne",
    nameKr: "샴페인",
    img: "https://www.thecocktaildb.com/images/ingredients/Champagne-Small.png",
  },
  {
    id: 5,
    name: "Scotch",
    nameKr: "스카치",
    img: "https://www.thecocktaildb.com/images/ingredients/Scotch-Small.png",
  },
  {
    id: 2,
    name: "Gin",
    nameKr: "진",
    img: "https://www.thecocktaildb.com/images/ingredients/Gin-Small.png",
  },
  {
    id: 81,
    name: "Cachaca",
    nameKr: "카샤샤",
    img: "https://www.thecocktaildb.com/images/ingredients/Cachaca-Small.png",
  },
  {
    id: 141,
    name: "Cognac",
    nameKr: "코냑",
    img: "https://www.thecocktaildb.com/images/ingredients/Cognac-Small.png",
  },
  {
    id: 542,
    name: "Prosecco",
    nameKr: "프로스코",
    img: "https://www.thecocktaildb.com/images/ingredients/Prosecco-Small.png",
  },
  {
    id: 523,
    name: "White Rum",
    nameKr: "화이트 럼",
    img: "https://www.thecocktaildb.com/images/ingredients/White Rum-Small.png",
  },
  {
    id: 525,
    name: "White Wine",
    nameKr: "화이트 와인",
    img: "https://www.thecocktaildb.com/images/ingredients/White Wine-Small.png",
  },
];

const liqueur: object[] = [
  {
    id: 223,
    name: "Galliano",
    nameKr: "갈리아노",
    img: "https://www.thecocktaildb.com/images/ingredients/Galliano-Small.png",
  },
  {
    id: 282,
    name: "Kahlua",
    nameKr: "깔루아",
    img: "https://www.thecocktaildb.com/images/ingredients/Kahlua-Small.png",
  },
  {
    id: 189,
    name: "Dry Vermouth",
    nameKr: "드라이 베르무트",
    img: "https://www.thecocktaildb.com/images/ingredients/Dry Vermouth-Small.png",
  },
  {
    id: 323,
    name: "Maraschino Liqueur",
    nameKr: "마라스키노 리큐르",
    img: "https://www.thecocktaildb.com/images/ingredients/Maraschino Liqueur-Small.png",
  },
  {
    id: 56,
    name: "Bitters",
    nameKr: "비터스",
    img: "https://www.thecocktaildb.com/images/ingredients/Bitters-Small.png",
  },
  {
    id: 32,
    name: "Apricot Brandy",
    nameKr: "살구 브랜디",
    img: "https://www.thecocktaildb.com/images/ingredients/Apricot Brandy-Small.png",
  },
  {
    id: 480,
    name: "Sweet and Sour",
    nameKr: "새콤달콤한 맛",
    img: "https://www.thecocktaildb.com/images/ingredients/Sweet and Sour-Small.png",
  },
  {
    id: 482,
    name: "Sweet Vermouth",
    nameKr: "스위트 베르무트",
    img: "https://www.thecocktaildb.com/images/ingredients/Sweet Vermouth-Small.png",
  },
  {
    id: 18,
    name: "Amaretto",
    nameKr: "아마레토",
    img: "https://www.thecocktaildb.com/images/ingredients/Amaretto-Small.png",
  },
  {
    id: 20,
    name: "Angostura Bitters",
    nameKr: "앙고스투라 비터스",
    img: "https://www.thecocktaildb.com/images/ingredients/Angostura Bitters-Small.png",
  },
  {
    id: 26,
    name: "Apple Brandy",
    nameKr: "애플 브랜디",
    img: "https://www.thecocktaildb.com/images/ingredients/Apple Brandy-Small.png",
  },
  {
    id: 552,
    name: "Elderflower cordial",
    nameKr: "엘더플라워 코디얼",
    img: "https://www.thecocktaildb.com/images/ingredients/Elderflower cordial-Small.png",
  },
  {
    id: 350,
    name: "Orange Bitters",
    nameKr: "오렌지 비터스",
    img: "https://www.thecocktaildb.com/images/ingredients/Orange Bitters-Small.png",
  },
  {
    id: 83,
    name: "Campari",
    nameKr: "캄파리",
    img: "https://www.thecocktaildb.com/images/ingredients/Campari-Small.png",
  },
  {
    id: 133,
    name: "Coconut Liqueur",
    nameKr: "코코넛 리큐어",
    img: "https://www.thecocktaildb.com/images/ingredients/Coconut Liqueur-Small.png",
  },
  {
    id: 142,
    name: "Cointreau",
    nameKr: "쿠앵트로",
    img: "https://www.thecocktaildb.com/images/ingredients/Cointreau-Small.png",
  },
  {
    id: 165,
    name: "Creme De Cassis",
    nameKr: "크레미 드 카시스",
    img: "https://www.thecocktaildb.com/images/ingredients/Creme De Cassis-Small.png",
  },
  {
    id: 164,
    name: "Creme De Cacao",
    nameKr: "크림 드 카카오",
    img: "https://www.thecocktaildb.com/images/ingredients/Creme De Cacao-Small.png",
  },
  {
    id: 498,
    name: "Triple Sec",
    nameKr: "트리플 섹",
    img: "https://www.thecocktaildb.com/images/ingredients/Triple Sec-Small.png",
  },
  {
    id: 374,
    name: "Passoa",
    nameKr: "파소아",
    img: "https://www.thecocktaildb.com/images/ingredients/Passoa-Small.png",
  },
  {
    id: 540,
    name: "Peach Bitters",
    nameKr: "피치 비터스",
    img: "https://www.thecocktaildb.com/images/ingredients/Peach Bitters-Small.png",
  },
  {
    id: 379,
    name: "Peach Schnapps",
    nameKr: "피치스냅스",
    img: "https://www.thecocktaildb.com/images/ingredients/Peach Schnapps-Small.png",
  },
];

const drinks: object[] = [
  {
    id: 308,
    name: "Lime Juice",
    nameKr: "라임 즙",
    img: "https://www.thecocktaildb.com/images/ingredients/Lime Juice-Small.png",
  },
  {
    id: 297,
    name: "Lemon-lime soda",
    nameKr: "레몬 라임 소다",
    img: "https://www.thecocktaildb.com/images/ingredients/Lemon-lime soda-Small.png",
  },
  {
    id: 293,
    name: "Lemon Juice",
    nameKr: "레몬 즙",
    img: "https://www.thecocktaildb.com/images/ingredients/Lemon Juice-Small.png",
  },
  {
    id: 300,
    name: "Lemonade",
    nameKr: "레몬에이드",
    img: "https://www.thecocktaildb.com/images/ingredients/Lemonade-Small.png",
  },
  {
    id: 513,
    name: "Water",
    nameKr: "물",
    img: "https://www.thecocktaildb.com/images/ingredients/Water-Small.png",
  },
  {
    id: 455,
    name: "Soda Water",
    nameKr: "소다수",
    img: "https://www.thecocktaildb.com/images/ingredients/Soda Water-Small.png",
  },
  {
    id: 28,
    name: "Apple Juice",
    nameKr: "애플 주스",
    img: "https://www.thecocktaildb.com/images/ingredients/Apple Juice-Small.png",
  },
  {
    id: 352,
    name: "Orange Juice",
    nameKr: "오렌지 주스",
    img: "https://www.thecocktaildb.com/images/ingredients/Orange Juice-Small.png",
  },
  {
    id: 229,
    name: "Ginger Beer",
    nameKr: "진저 맥주",
    img: "https://www.thecocktaildb.com/images/ingredients/Ginger Beer-Small.png",
  },
  {
    id: 228,
    name: "Ginger Ale",
    nameKr: "진저 에일",
    img: "https://www.thecocktaildb.com/images/ingredients/Ginger Ale-Small.png",
  },
  {
    id: 139,
    name: "Coffee",
    nameKr: "커피",
    img: "https://www.thecocktaildb.com/images/ingredients/Coffee-Small.png",
  },
  {
    id: 128,
    name: "Coca-Cola",
    nameKr: "코카콜라",
    img: "https://www.thecocktaildb.com/images/ingredients/Coca-Cola-Small.png",
  },
  {
    id: 155,
    name: "Cranberry Juice",
    nameKr: "크랜베리 주스",
    img: "https://www.thecocktaildb.com/images/ingredients/Cranberry Juice-Small.png",
  },
  {
    id: 89,
    name: "Carbonated Water",
    nameKr: "탄산수",
    img: "https://www.thecocktaildb.com/images/ingredients/Carbonated Water-Small.png",
  },
  {
    id: 492,
    name: "Tomato Juice",
    nameKr: "토마토 주스",
    img: "https://www.thecocktaildb.com/images/ingredients/Tomato Juice-Small.png",
  },
  {
    id: 393,
    name: "Pineapple Juice",
    nameKr: "파인애플 주스",
    img: "https://www.thecocktaildb.com/images/ingredients/Pineapple Juice-Small.png",
  },
  {
    id: 372,
    name: "Passion fruit juice",
    nameKr: "패션 과일 주스",
    img: "https://www.thecocktaildb.com/images/ingredients/Passion fruit juice-Small.png",
  },
  {
    id: 242,
    name: "Grapefruit Juice",
    nameKr: "포도 주스",
    img: "https://www.thecocktaildb.com/images/ingredients/Grapefruit Juice-Small.png",
  },
];

const ingredients: object[] = [
  {
    id: 122,
    name: "Cinnamon",
    nameKr: "계피",
    img: "https://www.thecocktaildb.com/images/ingredients/Cinnamon-Small.png",
  },
  {
    id: 409,
    name: "Powdered Sugar",
    nameKr: "고운 설탕",
    img: "https://www.thecocktaildb.com/images/ingredients/Powdered Sugar-Small.png",
  },
  {
    id: 250,
    name: "Grenadine",
    nameKr: "그레나딘",
    img: "https://www.thecocktaildb.com/images/ingredients/Grenadine-Small.png",
  },
  {
    id: 260,
    name: "Honey",
    nameKr: "꿀",
    img: "https://www.thecocktaildb.com/images/ingredients/Honey-Small.png",
  },
  {
    id: 470,
    name: "Strawberries",
    nameKr: "딸기",
    img: "https://www.thecocktaildb.com/images/ingredients/Strawberries-Small.png",
  },
  {
    id: 304,
    name: "Light Cream",
    nameKr: "라이트 크림",
    img: "https://www.thecocktaildb.com/images/ingredients/Light Cream-Small.png",
  },
  {
    id: 312,
    name: "Lime",
    nameKr: "라임",
    img: "https://www.thecocktaildb.com/images/ingredients/Lime-Small.png",
  },
  {
    id: 299,
    name: "lemon",
    nameKr: "레몬",
    img: "https://www.thecocktaildb.com/images/ingredients/lemon-Small.png",
  },
  {
    id: 294,
    name: "Lemon Peel",
    nameKr: "레몬 껍질",
    img: "https://www.thecocktaildb.com/images/ingredients/Lemon Peel-Small.png",
  },
  {
    id: 322,
    name: "Maraschino Cherry",
    nameKr: "마라스키노 체리",
    img: "https://www.thecocktaildb.com/images/ingredients/Maraschino Cherry-Small.png",
  },
  {
    id: 319,
    name: "Mango",
    nameKr: "망고",
    img: "https://www.thecocktaildb.com/images/ingredients/Mango-Small.png",
  },
  {
    id: 337,
    name: "Mint",
    nameKr: "민트",
    img: "https://www.thecocktaildb.com/images/ingredients/Mint-Small.png",
  },
  {
    id: 77,
    name: "Brown Sugar",
    nameKr: "브라운 슈가",
    img: "https://www.thecocktaildb.com/images/ingredients/Brown Sugar-Small.png",
  },
  {
    id: 60,
    name: "Blackberries",
    nameKr: "블랙베리",
    img: "https://www.thecocktaildb.com/images/ingredients/Blackberries-Small.png",
  },
  {
    id: 67,
    name: "Blue Curacao",
    nameKr: "블루 큐라소",
    img: "https://www.thecocktaildb.com/images/ingredients/Blue Curacao-Small.png",
  },
  {
    id: 69,
    name: "Blueberries",
    nameKr: "블루베리",
    img: "https://www.thecocktaildb.com/images/ingredients/Blueberries-Small.png",
  },
  {
    id: 30,
    name: "Apple",
    nameKr: "사과",
    img: "https://www.thecocktaildb.com/images/ingredients/Apple-Small.png",
  },
  {
    id: 476,
    name: "Sugar",
    nameKr: "설탕",
    img: "https://www.thecocktaildb.com/images/ingredients/Sugar-Small.png",
  },
  {
    id: 94,
    name: "Celery Salt",
    nameKr: "셀러리 소금",
    img: "https://www.thecocktaildb.com/images/ingredients/Celery Salt-Small.png",
  },
  {
    id: 448,
    name: "Sherbet",
    nameKr: "셔벗",
    img: "https://www.thecocktaildb.com/images/ingredients/Sherbet-Small.png",
  },
  {
    id: 439,
    name: "Salt",
    nameKr: "소금",
    img: "https://www.thecocktaildb.com/images/ingredients/Salt-Small.png",
  },
  {
    id: 475,
    name: "Sugar Syrup",
    nameKr: "시럽",
    img: "https://www.thecocktaildb.com/images/ingredients/Sugar Syrup-Small.png",
  },
  {
    id: 12,
    name: "Agave Syrup",
    nameKr: "아가베 시럽",
    img: "https://www.thecocktaildb.com/images/ingredients/Agave Syrup-Small.png",
  },
  {
    id: 270,
    name: "Ice",
    nameKr: "얼음",
    img: "https://www.thecocktaildb.com/images/ingredients/Ice-Small.png",
  },
  {
    id: 192,
    name: "Egg White",
    nameKr: "에그 화이트",
    img: "https://www.thecocktaildb.com/images/ingredients/Egg White-Small.png",
  },
  {
    id: 359,
    name: "Orange",
    nameKr: "오렌지",
    img: "https://www.thecocktaildb.com/images/ingredients/Orange-Small.png",
  },
  {
    id: 354,
    name: "Orange Peel",
    nameKr: "오렌지 껍질",
    img: "https://www.thecocktaildb.com/images/ingredients/Orange Peel-Small.png",
  },
  {
    id: 362,
    name: "Orgeat Syrup",
    nameKr: "오르간 시럽",
    img: "https://www.thecocktaildb.com/images/ingredients/Orgeat Syrup-Small.png",
  },
  {
    id: 347,
    name: "Olive",
    nameKr: "올리브",
    img: "https://www.thecocktaildb.com/images/ingredients/Olive-Small.png",
  },
  {
    id: 533,
    name: "Yoghurt",
    nameKr: "요거트",
    img: "https://www.thecocktaildb.com/images/ingredients/Yoghurt-Small.png",
  },
  {
    id: 529,
    name: "Worcestershire Sauce",
    nameKr: "우스터 소스",
    img: "https://www.thecocktaildb.com/images/ingredients/Worcestershire Sauce-Small.png",
  },
  {
    id: 344,
    name: "Nutmeg",
    nameKr: "육두구",
    img: "https://www.thecocktaildb.com/images/ingredients/Nutmeg-Small.png",
  },
  {
    id: 126,
    name: "Cloves",
    nameKr: "정향",
    img: "https://www.thecocktaildb.com/images/ingredients/Cloves-Small.png",
  },
  {
    id: 230,
    name: "Ginger",
    nameKr: "진저",
    img: "https://www.thecocktaildb.com/images/ingredients/Ginger-Small.png",
  },
  {
    id: 106,
    name: "Cherry",
    nameKr: "체리",
    img: "https://www.thecocktaildb.com/images/ingredients/Cherry-Small.png",
  },
  {
    id: 161,
    name: "Cream",
    nameKr: "크림",
    img: "https://www.thecocktaildb.com/images/ingredients/Cream-Small.png",
  },
  {
    id: 286,
    name: "Kiwi",
    nameKr: "키위",
    img: "https://www.thecocktaildb.com/images/ingredients/Kiwi-Small.png",
  },
  {
    id: 483,
    name: "Tabasco Sauce",
    nameKr: "타바스코 소스",
    img: "https://www.thecocktaildb.com/images/ingredients/Tabasco Sauce-Small.png",
  },
  {
    id: 397,
    name: "Pineapple",
    nameKr: "파인애플",
    img: "https://www.thecocktaildb.com/images/ingredients/Pineapple-Small.png",
  },
];

export { baseAlcohol, liqueur, drinks, ingredients };
