const baseAlcohol: object[] = [
  {
    id: 179,
    name: "Dark Rum",
    nameKr: "다크럼",
    img: "https://www.thecocktaildb.com/images/ingredients/Dark Rum.png",
  },
  {
    id: 4,
    name: "Tequila",
    nameKr: "데킬라",
    img: "https://www.thecocktaildb.com/images/ingredients/Tequila.png",
  },
  {
    id: 305,
    name: "Light Rum",
    nameKr: "라이트 럼",
    img: "https://www.thecocktaildb.com/images/ingredients/Light Rum.png",
  },
  {
    id: 3,
    name: "Rum",
    nameKr: "럼",
    img: "https://www.thecocktaildb.com/images/ingredients/Rum.png",
  },
  {
    id: 1,
    name: "Vodka",
    nameKr: "보드카",
    img: "https://www.thecocktaildb.com/images/ingredients/Vodka.png",
  },
  {
    id: 71,
    name: "Bourbon",
    nameKr: "부르봉",
    img: "https://www.thecocktaildb.com/images/ingredients/Bourbon.png",
  },
  {
    id: 74,
    name: "Brandy",
    nameKr: "브랜디",
    img: "https://www.thecocktaildb.com/images/ingredients/Brandy.png",
  },
  {
    id: 97,
    name: "Champagne",
    nameKr: "샴페인",
    img: "https://www.thecocktaildb.com/images/ingredients/Champagne.png",
  },
  {
    id: 5,
    name: "Scotch",
    nameKr: "스카치",
    img: "https://www.thecocktaildb.com/images/ingredients/Scotch.png",
  },
  {
    id: 2,
    name: "Gin",
    nameKr: "진",
    img: "https://www.thecocktaildb.com/images/ingredients/Gin.png",
  },
  {
    id: 81,
    name: "Cachaca",
    nameKr: "카샤샤",
    img: "https://www.thecocktaildb.com/images/ingredients/Cachaca.png",
  },
  {
    id: 141,
    name: "Cognac",
    nameKr: "코냑",
    img: "https://www.thecocktaildb.com/images/ingredients/Cognac.png",
  },
  {
    id: 542,
    name: "Prosecco",
    nameKr: "프로스코",
    img: "https://www.thecocktaildb.com/images/ingredients/Prosecco.png",
  },
  {
    id: 523,
    name: "White Rum",
    nameKr: "화이트 럼",
    img: "https://www.thecocktaildb.com/images/ingredients/White Rum.png",
  },
  {
    id: 525,
    name: "White Wine",
    nameKr: "화이트 와인",
    img: "https://www.thecocktaildb.com/images/ingredients/White Wine.png",
  },
];

const liqueur: object[] = [
  {
    id: 223,
    name: "Galliano",
    nameKr: "갈리아노",
    img: "https://www.thecocktaildb.com/images/ingredients/Galliano.png",
  },
  {
    id: 282,
    name: "Kahlua",
    nameKr: "깔루아",
    img: "https://www.thecocktaildb.com/images/ingredients/Kahlua.png",
  },
  {
    id: 189,
    name: "Dry Vermouth",
    nameKr: "드라이 베르무트",
    img: "https://www.thecocktaildb.com/images/ingredients/Dry Vermouth.png",
  },
  {
    id: 323,
    name: "Maraschino Liqueur",
    nameKr: "마라스키노 리큐르",
    img: "https://www.thecocktaildb.com/images/ingredients/Maraschino Liqueur.png",
  },
  {
    id: 56,
    name: "Bitters",
    nameKr: "비터스",
    img: "https://www.thecocktaildb.com/images/ingredients/Bitters.png",
  },
  {
    id: 32,
    name: "Apricot Brandy",
    nameKr: "살구 브랜디",
    img: "https://www.thecocktaildb.com/images/ingredients/Apricot Brandy.png",
  },
  {
    id: 480,
    name: "Sweet and Sour",
    nameKr: "새콤달콤한 맛",
    img: "https://www.thecocktaildb.com/images/ingredients/Sweet and Sour.png",
  },
  {
    id: 482,
    name: "Sweet Vermouth",
    nameKr: "스위트 베르무트",
    img: "https://www.thecocktaildb.com/images/ingredients/Sweet Vermouth.png",
  },
  {
    id: 18,
    name: "Amaretto",
    nameKr: "아마레토",
    img: "https://www.thecocktaildb.com/images/ingredients/Amaretto.png",
  },
  {
    id: 20,
    name: "Angostura Bitters",
    nameKr: "앙고스투라 비터스",
    img: "https://www.thecocktaildb.com/images/ingredients/Angostura Bitters.png",
  },
  {
    id: 26,
    name: "Apple Brandy",
    nameKr: "애플 브랜디",
    img: "https://www.thecocktaildb.com/images/ingredients/Apple Brandy.png",
  },
  {
    id: 552,
    name: "Elderflower cordial",
    nameKr: "엘더플라워 코디얼",
    img: "https://www.thecocktaildb.com/images/ingredients/Elderflower cordial.png",
  },
  {
    id: 350,
    name: "Orange Bitters",
    nameKr: "오렌지 비터스",
    img: "https://www.thecocktaildb.com/images/ingredients/Orange Bitters.png",
  },
  {
    id: 83,
    name: "Campari",
    nameKr: "캄파리",
    img: "https://www.thecocktaildb.com/images/ingredients/Campari.png",
  },
  {
    id: 133,
    name: "Coconut Liqueur",
    nameKr: "코코넛 리큐어",
    img: "https://www.thecocktaildb.com/images/ingredients/Coconut Liqueur.png",
  },
  {
    id: 142,
    name: "Cointreau",
    nameKr: "쿠앵트로",
    img: "https://www.thecocktaildb.com/images/ingredients/Cointreau.png",
  },
  {
    id: 165,
    name: "Creme De Cassis",
    nameKr: "크레미 드 카시스",
    img: "https://www.thecocktaildb.com/images/ingredients/Creme De Cassis.png",
  },
  {
    id: 164,
    name: "Creme De Cacao",
    nameKr: "크림 드 카카오",
    img: "https://www.thecocktaildb.com/images/ingredients/Creme De Cacao.png",
  },
  {
    id: 498,
    name: "Triple Sec",
    nameKr: "트리플 섹",
    img: "https://www.thecocktaildb.com/images/ingredients/Triple Sec.png",
  },
  {
    id: 374,
    name: "Passoa",
    nameKr: "파소아",
    img: "https://www.thecocktaildb.com/images/ingredients/Passoa.png",
  },
  {
    id: 540,
    name: "Peach Bitters",
    nameKr: "피치 비터스",
    img: "https://www.thecocktaildb.com/images/ingredients/Peach Bitters.png",
  },
  {
    id: 379,
    name: "Peach Schnapps",
    nameKr: "피치스냅스",
    img: "https://www.thecocktaildb.com/images/ingredients/Peach Schnapps.png",
  },
];

const drinks: object[] = [
  {
    id: 308,
    name: "Lime Juice",
    nameKr: "라임 즙",
    img: "https://www.thecocktaildb.com/images/ingredients/Lime Juice.png",
  },
  {
    id: 297,
    name: "Lemon-lime soda",
    nameKr: "레몬 라임 소다",
    img: "https://www.thecocktaildb.com/images/ingredients/Lemon-lime soda.png",
  },
  {
    id: 293,
    name: "Lemon Juice",
    nameKr: "레몬 즙",
    img: "https://www.thecocktaildb.com/images/ingredients/Lemon Juice.png",
  },
  {
    id: 300,
    name: "Lemonade",
    nameKr: "레몬에이드",
    img: "https://www.thecocktaildb.com/images/ingredients/Lemonade.png",
  },
  {
    id: 513,
    name: "Water",
    nameKr: "물",
    img: "https://www.thecocktaildb.com/images/ingredients/Water.png",
  },
  {
    id: 455,
    name: "Soda Water",
    nameKr: "소다수",
    img: "https://www.thecocktaildb.com/images/ingredients/Soda Water.png",
  },
  {
    id: 28,
    name: "Apple Juice",
    nameKr: "애플 주스",
    img: "https://www.thecocktaildb.com/images/ingredients/Apple Juice.png",
  },
  {
    id: 352,
    name: "Orange Juice",
    nameKr: "오렌지 주스",
    img: "https://www.thecocktaildb.com/images/ingredients/Orange Juice.png",
  },
  {
    id: 229,
    name: "Ginger Beer",
    nameKr: "진저 맥주",
    img: "https://www.thecocktaildb.com/images/ingredients/Ginger Beer.png",
  },
  {
    id: 228,
    name: "Ginger Ale",
    nameKr: "진저 에일",
    img: "https://www.thecocktaildb.com/images/ingredients/Ginger Ale.png",
  },
  {
    id: 139,
    name: "Coffee",
    nameKr: "커피",
    img: "https://www.thecocktaildb.com/images/ingredients/Coffee.png",
  },
  {
    id: 128,
    name: "Coca-Cola",
    nameKr: "코카콜라",
    img: "https://www.thecocktaildb.com/images/ingredients/Coca-Cola.png",
  },
  {
    id: 155,
    name: "Cranberry Juice",
    nameKr: "크랜베리 주스",
    img: "https://www.thecocktaildb.com/images/ingredients/Cranberry Juice.png",
  },
  {
    id: 89,
    name: "Carbonated Water",
    nameKr: "탄산수",
    img: "https://www.thecocktaildb.com/images/ingredients/Carbonated Water.png",
  },
  {
    id: 492,
    name: "Tomato Juice",
    nameKr: "토마토 주스",
    img: "https://www.thecocktaildb.com/images/ingredients/Tomato Juice.png",
  },
  {
    id: 393,
    name: "Pineapple Juice",
    nameKr: "파인애플 주스",
    img: "https://www.thecocktaildb.com/images/ingredients/Pineapple Juice.png",
  },
  {
    id: 372,
    name: "Passion fruit juice",
    nameKr: "패션 과일 주스",
    img: "https://www.thecocktaildb.com/images/ingredients/Passion fruit juice.png",
  },
  {
    id: 242,
    name: "Grapefruit Juice",
    nameKr: "포도 주스",
    img: "https://www.thecocktaildb.com/images/ingredients/Grapefruit Juice.png",
  },
];

const ingredients: object[] = [
  {
    id: 122,
    name: "Cinnamon",
    nameKr: "계피",
    img: "https://www.thecocktaildb.com/images/ingredients/Cinnamon.png",
  },
  {
    id: 409,
    name: "Powdered Sugar",
    nameKr: "고운 설탕",
    img: "https://www.thecocktaildb.com/images/ingredients/Powdered Sugar.png",
  },
  {
    id: 250,
    name: "Grenadine",
    nameKr: "그레나딘",
    img: "https://www.thecocktaildb.com/images/ingredients/Grenadine.png",
  },
  {
    id: 260,
    name: "Honey",
    nameKr: "꿀",
    img: "https://www.thecocktaildb.com/images/ingredients/Honey.png",
  },
  {
    id: 470,
    name: "Strawberries",
    nameKr: "딸기",
    img: "https://www.thecocktaildb.com/images/ingredients/Strawberries.png",
  },
  {
    id: 304,
    name: "Light Cream",
    nameKr: "라이트 크림",
    img: "https://www.thecocktaildb.com/images/ingredients/Light Cream.png",
  },
  {
    id: 312,
    name: "Lime",
    nameKr: "라임",
    img: "https://www.thecocktaildb.com/images/ingredients/Lime.png",
  },
  {
    id: 299,
    name: "lemon",
    nameKr: "레몬",
    img: "https://www.thecocktaildb.com/images/ingredients/lemon.png",
  },
  {
    id: 294,
    name: "Lemon Peel",
    nameKr: "레몬 껍질",
    img: "https://www.thecocktaildb.com/images/ingredients/Lemon Peel.png",
  },
  {
    id: 322,
    name: "Maraschino Cherry",
    nameKr: "마라스키노 체리",
    img: "https://www.thecocktaildb.com/images/ingredients/Maraschino Cherry.png",
  },
  {
    id: 319,
    name: "Mango",
    nameKr: "망고",
    img: "https://www.thecocktaildb.com/images/ingredients/Mango.png",
  },
  {
    id: 337,
    name: "Mint",
    nameKr: "민트",
    img: "https://www.thecocktaildb.com/images/ingredients/Mint.png",
  },
  {
    id: 77,
    name: "Brown Sugar",
    nameKr: "브라운 슈가",
    img: "https://www.thecocktaildb.com/images/ingredients/Brown Sugar.png",
  },
  {
    id: 60,
    name: "Blackberries",
    nameKr: "블랙베리",
    img: "https://www.thecocktaildb.com/images/ingredients/Blackberries.png",
  },
  {
    id: 67,
    name: "Blue Curacao",
    nameKr: "블루 큐라소",
    img: "https://www.thecocktaildb.com/images/ingredients/Blue Curacao.png",
  },
  {
    id: 69,
    name: "Blueberries",
    nameKr: "블루베리",
    img: "https://www.thecocktaildb.com/images/ingredients/Blueberries.png",
  },
  {
    id: 30,
    name: "Apple",
    nameKr: "사과",
    img: "https://www.thecocktaildb.com/images/ingredients/Apple.png",
  },
  {
    id: 476,
    name: "Sugar",
    nameKr: "설탕",
    img: "https://www.thecocktaildb.com/images/ingredients/Sugar.png",
  },
  {
    id: 94,
    name: "Celery Salt",
    nameKr: "셀러리 소금",
    img: "https://www.thecocktaildb.com/images/ingredients/Celery Salt.png",
  },
  {
    id: 448,
    name: "Sherbet",
    nameKr: "셔벗",
    img: "https://www.thecocktaildb.com/images/ingredients/Sherbet.png",
  },
  {
    id: 439,
    name: "Salt",
    nameKr: "소금",
    img: "https://www.thecocktaildb.com/images/ingredients/Salt.png",
  },
  {
    id: 475,
    name: "Sugar Syrup",
    nameKr: "시럽",
    img: "https://www.thecocktaildb.com/images/ingredients/Sugar Syrup.png",
  },
  {
    id: 12,
    name: "Agave Syrup",
    nameKr: "아가베 시럽",
    img: "https://www.thecocktaildb.com/images/ingredients/Agave Syrup.png",
  },
  {
    id: 270,
    name: "Ice",
    nameKr: "얼음",
    img: "https://www.thecocktaildb.com/images/ingredients/Ice.png",
  },
  {
    id: 192,
    name: "Egg White",
    nameKr: "에그 화이트",
    img: "https://www.thecocktaildb.com/images/ingredients/Egg White.png",
  },
  {
    id: 359,
    name: "Orange",
    nameKr: "오렌지",
    img: "https://www.thecocktaildb.com/images/ingredients/Orange.png",
  },
  {
    id: 354,
    name: "Orange Peel",
    nameKr: "오렌지 껍질",
    img: "https://www.thecocktaildb.com/images/ingredients/Orange Peel.png",
  },
  {
    id: 362,
    name: "Orgeat Syrup",
    nameKr: "오르간 시럽",
    img: "https://www.thecocktaildb.com/images/ingredients/Orgeat Syrup.png",
  },
  {
    id: 347,
    name: "Olive",
    nameKr: "올리브",
    img: "https://www.thecocktaildb.com/images/ingredients/Olive.png",
  },
  {
    id: 533,
    name: "Yoghurt",
    nameKr: "요거트",
    img: "https://www.thecocktaildb.com/images/ingredients/Yoghurt.png",
  },
  {
    id: 529,
    name: "Worcestershire Sauce",
    nameKr: "우스터 소스",
    img: "https://www.thecocktaildb.com/images/ingredients/Worcestershire Sauce.png",
  },
  {
    id: 344,
    name: "Nutmeg",
    nameKr: "육두구",
    img: "https://www.thecocktaildb.com/images/ingredients/Nutmeg.png",
  },
  {
    id: 126,
    name: "Cloves",
    nameKr: "정향",
    img: "https://www.thecocktaildb.com/images/ingredients/Cloves.png",
  },
  {
    id: 230,
    name: "Ginger",
    nameKr: "진저",
    img: "https://www.thecocktaildb.com/images/ingredients/Ginger.png",
  },
  {
    id: 106,
    name: "Cherry",
    nameKr: "체리",
    img: "https://www.thecocktaildb.com/images/ingredients/Cherry.png",
  },
  {
    id: 161,
    name: "Cream",
    nameKr: "크림",
    img: "https://www.thecocktaildb.com/images/ingredients/Cream.png",
  },
  {
    id: 286,
    name: "Kiwi",
    nameKr: "키위",
    img: "https://www.thecocktaildb.com/images/ingredients/Kiwi.png",
  },
  {
    id: 483,
    name: "Tabasco Sauce",
    nameKr: "타바스코 소스",
    img: "https://www.thecocktaildb.com/images/ingredients/Tabasco Sauce.png",
  },
  {
    id: 397,
    name: "Pineapple",
    nameKr: "파인애플",
    img: "https://www.thecocktaildb.com/images/ingredients/Pineapple.png",
  },
];

export { baseAlcohol, liqueur, drinks, ingredients };
