spring:
  mvc:
    static-path-pattern: /img/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/juadb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    url: jdbc:mariadb://localhost:3306/juadb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: "jdbc:mysql://localhost:3306/JuaDB?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
#    username: root
#    password: nh0455k8613!

#    username: root
#    password: 1q2w3e4r!@#
#    username: root
#    password: 1q2w3e4r!@#


    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-backend
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  redis:
    host: redis
#    host: localhost
    port: 6379
#    password: 1q2w3e4r!@#
#cloud:
#  aws:
#    s3:
#      bucket: jourgeois-profile-image
#    region:
#      static: ap-northeast-2
#    credentials:
#      accessKey: AKIA3UA3EZT64ZXACMGY
#      secretKey: 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
#    stack:
#      auto: false
jwt:
  secret-key: secret-key-ssafy-daejeon-jourgeois-service-HS512-algorithm
  token-validity-in-sec: 5
  refresh-token-validity-in-sec: 604800
server:
  port: 8080

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    stack:
      auto: false
