#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 217608233279-k2op58rvkdtbbteakk7ag0tp5ia54mij.apps.googleusercontent.com
#            client-secret: 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
#            scope: profile, email
#
#          kakao:
#            client-id: f1c36f65322c75f1f28caf1560a306d1
#            redirect-uri: "http://localhost:8080/member/login/kakao/redirect"
#            client-authentication-method: POST
#            authorization-grant-type: authorization_code
#            scope: profile_nickname, profile_image, account_email
#            client-name: Kakao
#
#          naver:
#            client-id: D0B_Xn9oGT7I_66h9Z4U
#            client-secret: s0nlFmnlzR
#            redirect-uri: "http://localhost:8080/member/login/naver/redirect" # (== http://localhost:8080/login/oauth2/code/naver)
#        provider:
#          kakao:
#            authorization_uri: https://kauth.kakao.com/oauth/authorize
#            token_uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user_name_attribute: id
#          naver:
#            authorization_uri: https://nid.naver.com/oauth2.0/authorize
#            token_uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user_name_attribute: response