spring:
  mvc:
    static-path-pattern: /img/**
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/juadb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    url: jdbc:mariadb://localhost:3307/juadb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 1q2w3e4r!@#
# 주석처리 해야혀~

    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-backend
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  redis:
    host: redis
#    host: localhost
#    password: 1q2w3e4r!@#
    port: 6379

jwt:
  secret-key: secret-key-ssafy-daejeon-jourgeois-service-HS512-algorithm
  token-validity-in-sec: 30
  refresh-token-validity-in-sec: 604800
server:
  port: 8080


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error


cloud:
  aws:
    stack:
      auto: false

firebase-configuration-file: ./serviceAccountKey.json
# 정리 한 번 합시다..

